apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-login-config
data:
  MYSQL_DB_HOST: 'mysql-login.default.svc.cluster.local'
  CHAT_ENDPOINT : '35.196.104.161'
  # TODO: update MYSQL_DB_USER and MYSQL_DB_PASSWORD to match the variables that you used 
  #       to install the MySQL service
  MYSQL_DB_USER: 'junanp'
  MYSQL_DB_PASSWORD: 'junanp'
  MYSQL_DB_PORT: '3306'
