apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
  labels:
    app: spring-login-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-login-service
  template:
    metadata:
      labels:
        app: spring-login-service
    spec:
      containers:
      - name: login-service
        image: task5.azurecr.io/task5-login-service:v1
        ports:
        - containerPort: 8080
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          requests:
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: spring-login-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-login-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-login-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization