apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
  labels:
    app: spring-login-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-login-service
  template:
    metadata:
      labels:
        app: spring-login-service
    spec:
      containers:
      - name: login-service
        image: gcr.io/gcp-docker-kubernetes-414008/task4-login-service:task4-login-service
        ports:
        - containerPort: 8080
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          requests:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: spring-login-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-login-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-login-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
